version: '3'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`${NEXTJS_DOMAIN}`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
      - "traefik.http.middlewares.nextjs-stripapi.stripprefix.prefixes=/api"
      - "traefik.http.routers.nextjs-api.rule=Host(`${NEXTJS_DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.nextjs-api.middlewares=nextjs-stripapi@docker"
      - "traefik.http.routers.nextjs-api.service=strapi"
    networks:
      - web

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`${STRAPI_DOMAIN}`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=myresolver"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"
    networks:
      - web

networks:
  web:
    external: true
