import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Provider } from "@/app/_utils/provider";
import localFont from "next/font/local";
import Header from "@/app/_components/header";
import Footer from "@/app/_components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mainFont = localFont(
  { src: './_fonts/Montserrat/Montserrat-VariableFont_wght.ttf', style: 'normal' })

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
    <body className={cn(mainFont.className, "bg-background text-foreground")}>
    <Provider>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Header/>
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>
        <Footer/>
      </ThemeProvider>
    </Provider>
    </body>
    </html>
  );
}
